#!/usr/bin/env bash
#script that displays lines containing the bash word
#allowing you to easily get the PID of your Bash process.
#The third line of your script must be # shellcheck disable=SC2009

ps -auxf | grep bash
