#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely.
#In between each iteration of the loop, add a sleep 2
#unless it is killed (by pressing Ctrl + C)

while true
do
    echo "To infinity and beyond"
    sleep 2
done
