#!/usr/bin/env bash
#script that displays To infinity and beyond indefinetly
#stops the "4-to_infinity_and_beyond" process. using kill

#method 1  pgrep -f 4-to_infinity_and_beyond | xargs kill -TERM

#method 2

kill "$(pgrep -f 4-to_infinity_and_beyond)"
