#!/usr/bin/env bash
#script that displays To infinity and beyond indefinetly
#stops the "4-to_infinity_and_beyond" process. withot using "kill of killall"
#method 1 pkill -15 "bash ./4-to_infinity_and_beyond" -f

#method 2

pkill -f "4-to_infinity_and_beyond"
