#!/usr/bin/env bash
#script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed

list=$(ls)  # used command substition because ls is a command

for VAR in $list    # loop through all filenames in current directory
do
    echo "$VAR" | cut -d "-" -f 2-  # cut the file when - is reached and returns the field 2 downwards
done
