#!/usr/bin/env bash
# Displays all acive IPv4 IPs on the machine it’s executed on.
#method 0
# ifconfig | awk -F "[: ]+" '/inet addr:/ { print $4 }'

# method 1
# ifconfig | grep -Eo 'inet ([0-9]{1,3}\.?){4}' | cut -d ' ' -f 2

#method 2
ifconfig -a | grep "inet addr" | cut -d " " -f12 | cut -d ":" -f2
